apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workflowai

bases:
  - ../../base

commonLabels:
  app.kubernetes.io/part-of: workflowai
  environment: production

resources:
  - ingress.yaml
  - hpa-api-gateway.yaml
  - hpa-frontend.yaml

images:
  - name: <ECR_URL>/workflowai/api-gateway
    newName: <ECR_URL>/workflowai/api-gateway
    newTag: sha-latest
  - name: <ECR_URL>/workflowai/ingestion
    newName: <ECR_URL>/workflowai/ingestion
    newTag: sha-latest
  - name: <ECR_URL>/workflowai/agent-orchestrator
    newName: <ECR_URL>/workflowai/agent-orchestrator
    newTag: sha-latest
  - name: <ECR_URL>/workflowai/indexing
    newName: <ECR_URL>/workflowai/indexing
    newTag: sha-latest
  - name: <ECR_URL>/workflowai/model-service
    newName: <ECR_URL>/workflowai/model-service
    newTag: sha-latest
  - name: <ECR_URL>/workflowai/metrics
    newName: <ECR_URL>/workflowai/metrics
    newTag: sha-latest
  - name: <ECR_URL>/workflowai/finetune
    newName: <ECR_URL>/workflowai/finetune
    newTag: sha-latest
  - name: <ECR_URL>/workflowai/frontend
    newName: <ECR_URL>/workflowai/frontend
    newTag: sha-latest
