apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workflowai

bases:
  - ../../base

commonLabels:
  app.kubernetes.io/part-of: workflowai
  environment: production

resources:
  - ingress.yaml
  - hpa-api-gateway.yaml
  - hpa-frontend.yaml

patches:
  - path: resource-patches.yaml

images:
  - name: 589528730663.dkr.ecr.ap-southeast-1.amazonaws.com/workflowai/api-gateway
    newName: 589528730663.dkr.ecr.ap-southeast-1.amazonaws.com/workflowai/api-gateway
    newTag: sha-1f3da29
  - name: 589528730663.dkr.ecr.ap-southeast-1.amazonaws.com/workflowai/ingestion
    newName: 589528730663.dkr.ecr.ap-southeast-1.amazonaws.com/workflowai/ingestion
    newTag: sha-47a7fbd
  - name: 589528730663.dkr.ecr.ap-southeast-1.amazonaws.com/workflowai/agent-orchestrator
    newName: 589528730663.dkr.ecr.ap-southeast-1.amazonaws.com/workflowai/agent-orchestrator
    newTag: sha-ea1c0b6
  - name: 589528730663.dkr.ecr.ap-southeast-1.amazonaws.com/workflowai/indexing
    newName: 589528730663.dkr.ecr.ap-southeast-1.amazonaws.com/workflowai/indexing
    newTag: sha-47a7fbd
  - name: 589528730663.dkr.ecr.ap-southeast-1.amazonaws.com/workflowai/model-service
    newName: 589528730663.dkr.ecr.ap-southeast-1.amazonaws.com/workflowai/model-service
    newTag: sha-7af4f76
  - name: 589528730663.dkr.ecr.ap-southeast-1.amazonaws.com/workflowai/metrics
    newName: 589528730663.dkr.ecr.ap-southeast-1.amazonaws.com/workflowai/metrics
    newTag: sha-47a7fbd
  - name: 589528730663.dkr.ecr.ap-southeast-1.amazonaws.com/workflowai/finetune
    newName: 589528730663.dkr.ecr.ap-southeast-1.amazonaws.com/workflowai/finetune
    newTag: sha-47a7fbd
  - name: 589528730663.dkr.ecr.ap-southeast-1.amazonaws.com/workflowai/frontend
    newName: 589528730663.dkr.ecr.ap-southeast-1.amazonaws.com/workflowai/frontend
    newTag: sha-47a7fbd
