apiVersion: v1
kind: Service
metadata:
  name: finetune
  namespace: workflowai
  labels:
    app: finetune
    component: service
spec:
  type: ClusterIP
  selector:
    app: finetune
  ports:
    - port: 8006
      targetPort: 8006
      name: http
