apiVersion: v1
kind: Service
metadata:
  name: indexing
  namespace: workflowai
  labels:
    app: indexing
    component: service
spec:
  type: ClusterIP
  selector:
    app: indexing
  ports:
    - port: 8003
      targetPort: 8003
      name: http
